name: bloc_learn
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.0.2
  equatable: ^2.0.3
  flow_builder: ^0.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  font_awesome_flutter: ^9.2.0
  form_inputs:
    path: packages/form_inputs
  formz: ^0.4.1
  google_fonts: ^2.2.0
  meta: ^1.7.0
  very_good_analysis: ^2.4.0

dev_dependencies:
  bloc_test: ^9.0.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/